创建一个形为5×3的二维数组，以包含5到10之间的随机数。

【知识点：随机抽样】

如何创建随机二维数组？

In [1]:
import numpy as np

np.random.seed(10)

In [2]:
x = np.random.randint(5, 10, [5, 3])
print(x)

[[6 9 5]
 [6 8 9]
 [6 5 6]
 [7 5 6]
 [5 7 5]]


In [3]:
x = np.random.uniform(5, 10, [5, 3])
print(x)

[[5.75188934 8.41909215 9.08300918]
 [6.68035792 9.45408265 5.99060907]
 [5.15308327 9.3880747  8.63717757]
 [7.70440466 5.65729076 7.06833687]
 [8.89364404 7.91950683 5.91315718]]
