# 普通文件

In [1]:
import numpy as np

outfile = r'.\task01.npy'
np.random.seed(20201123)

In [2]:
x = np.random.uniform(0, 1, [3, 5])

In [3]:
x

array([[0.03911501, 0.91357784, 0.21820335, 0.61869406, 0.25371066],
       [0.75731372, 0.16270282, 0.77498589, 0.41520052, 0.15138986],
       [0.34765902, 0.22682386, 0.80095883, 0.39216596, 0.79913296]])

In [4]:
np.save(outfile, x)

In [5]:
y = np.load(outfile)

In [6]:
y

array([[0.03911501, 0.91357784, 0.21820335, 0.61869406, 0.25371066],
       [0.75731372, 0.16270282, 0.77498589, 0.41520052, 0.15138986],
       [0.34765902, 0.22682386, 0.80095883, 0.39216596, 0.79913296]])

# 压缩文件

In [7]:
import numpy as np

outfile = r'.\task01.npz'
x = np.linspace(0, np.pi, 5)
y = np.sin(x)
z = np.cos(x)
np.savez(outfile, x, y, z_d=z)
data = np.load(outfile)
np.set_printoptions(suppress=True)

In [8]:
print(data.files)  

['z_d', 'arr_0', 'arr_1']


In [9]:
print(data['arr_0'])

[0.         0.78539816 1.57079633 2.35619449 3.14159265]


In [10]:
print(data['arr_1'])

[0.         0.70710678 1.         0.70710678 0.        ]


In [11]:
print(data['z_d'])

[ 1.          0.70710678  0.         -0.70710678 -1.        ]


# 文本文件

In [13]:
import numpy as np

outfile = r'.\task01.txt'
x = np.arange(0, 10).reshape(2, -1)
np.savetxt(outfile, x)
y = np.loadtxt(outfile)
print(y)

[[0. 1. 2. 3. 4.]
 [5. 6. 7. 8. 9.]]


# 课后练习

## 只打印或显示numpy数组rand_arr的小数点后3位。
- rand_arr = np.random.random([5, 3])


In [14]:
rand_arr = np.random.random([5, 3])
print(rand_arr)

[[0.60445173 0.93020507 0.94211434]
 [0.08940629 0.93638416 0.9169674 ]
 [0.78891615 0.37806171 0.66278257]
 [0.94917222 0.29985542 0.01311358]
 [0.89203232 0.22827152 0.18311075]]


In [15]:
np.set_printoptions(precision=3)

In [16]:
print(rand_arr)

[[0.604 0.93  0.942]
 [0.089 0.936 0.917]
 [0.789 0.378 0.663]
 [0.949 0.3   0.013]
 [0.892 0.228 0.183]]


## 将numpy数组a中打印的项数限制为最多6个元素。

In [18]:
import numpy as np
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
np.set_printoptions(threshold=6)
print(a)

[0 1 2 ... 7 8 9]


## 打印完整的numpy数组a而不中断。

In [21]:
import numpy as np
np.set_printoptions(threshold=20)
a=np.arange(50)
print(a)

[ 0  1  2 ... 47 48 49]


In [23]:
np.set_printoptions(threshold=np.iinfo(np.int).max)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]
