# 计算最小值

In [1]:
import numpy as np

x = np.arange(11,36).reshape(5,5)
print(x)

[[11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]
 [26 27 28 29 30]
 [31 32 33 34 35]]


In [2]:
np.amin(x)

11

In [3]:
np.amin(x, axis=0)

array([11, 12, 13, 14, 15])

In [4]:
np.amin(x, axis=1)

array([11, 16, 21, 26, 31])

# 计算最大值

In [5]:
np.amax(x)

35

In [6]:
np.amax(x, axis=0)

array([31, 32, 33, 34, 35])

In [7]:
np.amax(x, axis=1)

array([15, 20, 25, 30, 35])

# 计算极差

In [9]:
np.random.seed(20201127)

In [14]:
x = np.random.randint(0,20,size=(4,5))

In [15]:
x

array([[12, 18,  3,  8, 11],
       [18, 18, 14,  5, 18],
       [19, 10, 17, 11,  5],
       [11, 11,  6, 15,  4]])

In [16]:
np.ptp(x)

16

In [17]:
np.ptp(x, axis=0)

array([ 8,  8, 14, 10, 14])

In [18]:
np.ptp(x, axis=1)

array([15, 13, 14, 11])

# 计算分位数

In [19]:
np.percentile(x, [25, 50])

array([ 7.5, 11. ])

In [20]:
np.percentile(x, [25,50], axis=0)

array([[11.75, 10.75,  5.25,  7.25,  4.75],
       [15.  , 14.5 , 10.  ,  9.5 ,  8.  ]])

In [21]:
np.percentile(x, [25,50], axis=1)

array([[ 8., 14., 10.,  6.],
       [11., 18., 11., 11.]])

# 计算中位数

In [22]:
np.median(x)

11.0

In [23]:
np.percentile(x, 50)

11.0

In [24]:
np.median(x, axis=0)

array([15. , 14.5, 10. ,  9.5,  8. ])

In [25]:
np.percentile(x, 50, axis=0)

array([15. , 14.5, 10. ,  9.5,  8. ])

In [26]:
np.median(x, axis=1)

array([11., 18., 11., 11.])

In [28]:
np.percentile(x, 50, axis=1)

array([11., 18., 11., 11.])

# 计算平均值

In [30]:
x = np.arange(11,36).reshape(5,5)

In [31]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [32]:
np.mean(x)

23.0

In [33]:
np.mean(x, axis=0)

array([21., 22., 23., 24., 25.])

In [34]:
np.mean(x, axis=1)

array([13., 18., 23., 28., 33.])

# 计算加权平均值

In [35]:
np.average(x)

23.0

In [36]:
np.average(x, axis=0)

array([21., 22., 23., 24., 25.])

In [37]:
np.average(x, axis=1)

array([13., 18., 23., 28., 33.])

In [38]:
y = np.arange(1,26).reshape(5,5)

In [39]:
y

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [41]:
np.average(x, weights=y)

27.0

In [42]:
np.average(x, weights=y, axis=0)

array([25.54545455, 26.16666667, 26.84615385, 27.57142857, 28.33333333])

In [43]:
np.average(x, weights=y, axis=1)

array([13.66666667, 18.25      , 23.15384615, 28.11111111, 33.08695652])

# 计算方差

In [44]:
x = np.arange(11,36).reshape(5,5)

In [45]:
x

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [46]:
np.var(x)

52.0

In [48]:
np.mean((np.mean(x)-x)**2)

52.0

In [49]:
np.var(x, ddof=1)

54.166666666666664

In [50]:
np.sum((np.mean(x)-x)**2)/(x.size -1)

54.166666666666664

In [51]:
np.var(x, axis=0)

array([50., 50., 50., 50., 50.])

In [52]:
np.var(x, axis=1)

array([2., 2., 2., 2., 2.])

# 计算标准差

In [53]:
np.std(x)

7.211102550927978

In [54]:
np.sqrt(np.var(x))

7.211102550927978

In [55]:
np.std(x, axis=0)

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [56]:
np.std(x, axis=1)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

# 计算协方差矩阵

In [57]:
x = [1, 2, 3, 4, 6]
y = [0, 2, 5, 6, 7]

In [58]:
np.cov(x)

array(3.7)

In [59]:
np.cov(y)

array(8.5)

In [60]:
np.cov(x,y)

array([[3.7 , 5.25],
       [5.25, 8.5 ]])