# 矩阵向量积

In [1]:
import numpy as np

In [5]:
x = np.array([1, 2, 3, 4, 5])
y = np.array([2, 3, 4, 5, 6])
print(np.dot(x, y))

70


In [6]:
x = np.array([[1, 2, 3], [3, 4, 5], [6, 7, 8]])
print(x)

[[1 2 3]
 [3 4 5]
 [6 7 8]]


In [7]:
y = np.array([[5, 4, 2], [1, 7, 9], [0, 4, 5]])
print(y)

[[5 4 2]
 [1 7 9]
 [0 4 5]]


In [8]:
np.dot(x,y)

array([[  7,  30,  35],
       [ 19,  60,  67],
       [ 37, 105, 115]])

In [9]:
np.dot(y,x)

array([[ 29,  40,  51],
       [ 76,  93, 110],
       [ 42,  51,  60]])

# 矩阵特征值与特征向量

In [10]:
# 创建一个对角矩阵！
x = np.diag((1, 2, 3))  
print(x)

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [11]:
print(np.linalg.eigvals(x))

[1. 2. 3.]


In [12]:
a, b = np.linalg.eig(x)  
# 特征值保存在a中，特征向量保存在b中
print(a)
print(b)

[1. 2. 3.]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [13]:
# 检验特征值与特征向量是否正确
for i in range(3): 
    if np.allclose(a[i] * b[:, i], np.dot(x, b[:, i])):
        print('Right')
    else:
        print('Error')

Right
Right
Right


## 判断对称阵是否为正定阵（特征值是否全部为正）

In [14]:
A = np.arange(16).reshape(4, 4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [15]:
A = A + A.T  # 将方阵转换成对称阵
print(A)

[[ 0  5 10 15]
 [ 5 10 15 20]
 [10 15 20 25]
 [15 20 25 30]]


In [16]:
B = np.linalg.eigvals(A)  # 求A的特征值
print(B)

[ 6.74165739e+01+0.00000000e+00j -7.41657387e+00+0.00000000e+00j
 -8.88285420e-17+1.82759332e-15j -8.88285420e-17-1.82759332e-15j]


In [17]:
# 判断是不是所有的特征值都大于0，用到了all函数，显然对称阵A不是正定的
if np.all(B > 0):
    print('Yes')
else:
    print('No')

No


# 矩阵分解

## 奇异值分解

In [18]:
A = np.array([[4, 11, 14], [8, 7, -2]])
print(A)

[[ 4 11 14]
 [ 8  7 -2]]


In [19]:
u, s, vh = np.linalg.svd(A, full_matrices=False)
print(u.shape)  
print(u)


print(s.shape)  
print(np.diag(s))


print(vh.shape) 
print(vh)

(2, 2)
[[-0.9486833  -0.31622777]
 [-0.31622777  0.9486833 ]]
(2,)
[[18.97366596  0.        ]
 [ 0.          9.48683298]]
(2, 3)
[[-0.33333333 -0.66666667 -0.66666667]
 [ 0.66666667  0.33333333 -0.66666667]]


In [20]:
a = np.dot(u, np.diag(s))
a = np.dot(a, vh)
print(a)

[[ 4. 11. 14.]
 [ 8.  7. -2.]]


In [21]:
A = np.array([[1, 1], [1, -2], [2, 1]])
print(A)


u, s, vh = np.linalg.svd(A, full_matrices=False)
print(u.shape) 
print(u)


print(s.shape)  
print(np.diag(s))


print(vh.shape)  
print(vh)


a = np.dot(u, np.diag(s))
a = np.dot(a, vh)
print(a)

[[ 1  1]
 [ 1 -2]
 [ 2  1]]
(3, 2)
[[-5.34522484e-01 -9.06988786e-17]
 [ 2.67261242e-01 -9.48683298e-01]
 [-8.01783726e-01 -3.16227766e-01]]
(2,)
[[2.64575131 0.        ]
 [0.         2.23606798]]
(2, 2)
[[-0.70710678 -0.70710678]
 [-0.70710678  0.70710678]]
[[ 1.  1.]
 [ 1. -2.]
 [ 2.  1.]]


应用场景：PCA